#ifndef CONF_H
#define CONF_H

#define DEBUG 1
#define LVGL_TICK_PERIOD_MS 2
#define LOOP_DELAY 2

#define SCREEN_WIDTH 240
#define SCREEN_HEIGHT 240

#define SHOWCASE 1

#define WIFI_DEFAULT_SSID "NMEA3WIFI"
#define WIFI_DEFAULT_PASSWORD "12345678"
#define WIFI_DEFAULT_IP "192.168.4.1"
#define WIFI_DEFAULT_UDP_PORT 2000
#define WIFI_DEFAULT_TCP_PORT 3000


#endif