/*
 * Copyright (C) 2024-2025 Davide Gessa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef BOARDS_H
#define BOARDS_H

/*
 * Board Selection
 * ===============
 * The board is selected via board_config.h which is auto-generated by the Makefile.
 * Use: make compile BOARD=lcd128  or  make compile BOARD=lcd4
 *
 * Supported boards:
 * - BOARD_LCD_128  : Waveshare ESP32-S3 1.28" Round Touch LCD (240x240, GC9A01, CST816S)
 * - BOARD_LCD_4    : Waveshare ESP32-S3 4" Touch LCD (480x480, ST7701, GT911)
 */

// Include board selection (auto-generated by Makefile)
#include "../board_config.h"

// Validate board selection
#if !defined(BOARD_LCD_128) && !defined(BOARD_LCD_4)
    #error "No board selected! Run 'make compile BOARD=lcd128' or 'make compile BOARD=lcd4'"
#endif

// Validate only one board is selected
#if defined(BOARD_LCD_128) && defined(BOARD_LCD_4)
    #error "Only one board can be selected at a time"
#endif

// Include the appropriate board configuration
#ifdef BOARD_LCD_128
    #include "board_lcd_128.h"
#endif

#ifdef BOARD_LCD_4
    #include "board_lcd_4.h"
#endif

// Common validation
#ifndef SCREEN_WIDTH
    #error "Board configuration must define SCREEN_WIDTH"
#endif
#ifndef SCREEN_HEIGHT
    #error "Board configuration must define SCREEN_HEIGHT"
#endif
#ifndef BOARD_NAME
    #error "Board configuration must define BOARD_NAME"
#endif

#endif // BOARDS_H
